{
 "title": "Azure Redis",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "DataSource",
    "label": "DataSource",
    "query": "grafana-azure-monitor-datasource"
   },
   {
    "name": "Subscriptions",
    "label": "Subscriptions",
    "query": {}
   },
   {
    "name": "ResourceGroup",
    "label": "Resource Group",
    "query": {}
   },
   {
    "name": "ResourceName",
    "label": "ResourceName",
    "query": {}
   },
   {
    "name": "location",
    "query": {}
   },
   {
    "name": "hostname",
    "query": {}
   },
   {
    "name": "size",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<table style=\"border-collapse: collapse; width: 100%;\">\n  <tr>\n    <td style=\"color: #6E9FFF;\">Redis Name:</td>\n    <td>${ResourceName}</td>\n    <td style=\"color: #6E9FFF;\">Host Name:</td>\n    <td>${hostname}</td>\n  </tr>\n  <tr>\n    <td style=\"color: #6E9FFF;\">Resource Group:</td>\n    <td>${ResourceGroup}</td>\n    <td style=\"color: #6E9FFF;\">Size:</td>\n    <td>${size}</td>\n  </tr>\n  <tr>\n    <td style=\"color: #6E9FFF;\">Location:</td>\n    <td>${location}</td>\n    <td style=\"color: #6E9FFF;\"></td>\n    <td></td>\n  </tr>\n</table>"
   },
   "targets": [
    {
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Maximum",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "ShardId", "value": "ShardId" }
      ],
      "metricName": "percentProcessorTime",
      "metricNamespace": "Microsoft.Cache/Redis",
      "resources": [
       { "resourceGroup": "$ResourceGroup", "resourceName": "$ResourceName" }
      ],
      "timeGrain": "PT1M",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Maximum",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "ShardId", "value": "ShardId" }
      ],
      "metricName": "usedmemorypercentage",
      "metricNamespace": "Microsoft.Cache/Redis",
      "resources": [
       { "resourceGroup": "$ResourceGroup", "resourceName": "$ResourceName" }
      ],
      "timeGrain": "PT1M",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    }
   ]
  },
  {
   "title": "Server Load",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Maximum",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "ShardId", "value": "ShardId" }
      ],
      "metricName": "serverLoad",
      "metricNamespace": "Microsoft.Cache/Redis",
      "resources": [
       { "resourceGroup": "$ResourceGroup", "resourceName": "$ResourceName" }
      ],
      "timeGrain": "PT1M",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    }
   ]
  },
  {
   "title": "Cache latency",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Average",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "ShardId", "value": "ShardId" }
      ],
      "metricName": "cacheLatency",
      "metricNamespace": "Microsoft.Cache/Redis",
      "resources": [
       { "resourceGroup": "$ResourceGroup", "resourceName": "$ResourceName" }
      ],
      "timeGrain": "PT1M",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    }
   ]
  },
  {
   "title": "Errors / Min",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Maximum",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "ShardId", "value": "ShardId" },
       { "text": "ErrorType", "value": "ErrorType" }
      ],
      "metricName": "errors",
      "metricNamespace": "Microsoft.Cache/Redis",
      "resources": [
       { "resourceGroup": "$ResourceGroup", "resourceName": "$ResourceName" }
      ],
      "timeGrain": "PT1M",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    }
   ]
  },
  {
   "title": "Connected Clients",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Maximum",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "ShardId", "value": "ShardId" }
      ],
      "metricName": "connectedclients",
      "metricNamespace": "Microsoft.Cache/Redis",
      "resources": [
       { "resourceGroup": "$ResourceGroup", "resourceName": "$ResourceName" }
      ],
      "timeGrain": "PT1M",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    }
   ]
  },
  {
   "title": "Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cache Hits vs Cache Miss",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "alias": "Cache Hits",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "ShardId", "value": "ShardId" }
      ],
      "metricName": "cachehits",
      "metricNamespace": "Microsoft.Cache/Redis",
      "resources": [
       { "resourceGroup": "$ResourceGroup", "resourceName": "$ResourceName" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    },
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "alias": "Cache Miss",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "ShardId", "value": "ShardId" }
      ],
      "metricName": "cachemisses",
      "metricNamespace": "Microsoft.Cache/Redis",
      "resources": [
       { "resourceGroup": "$ResourceGroup", "resourceName": "$ResourceName" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    }
   ]
  },
  {
   "title": "Operations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "alias": "Total Operations",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "ShardId", "value": "ShardId" }
      ],
      "metricName": "totalcommandsprocessed",
      "metricNamespace": "Microsoft.Cache/Redis",
      "resources": [
       { "resourceGroup": "$ResourceGroup", "resourceName": "$ResourceName" }
      ],
      "timeGrain": "PT5M",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    },
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Maximum",
      "alias": "Operations / sec",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "ShardId", "value": "ShardId" }
      ],
      "metricName": "operationsPerSecond",
      "metricNamespace": "Microsoft.Cache/Redis",
      "resources": [
       { "resourceGroup": "$ResourceGroup", "resourceName": "$ResourceName" }
      ],
      "timeGrain": "PT5M",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    }
   ]
  },
  {
   "title": "Cache Read vs Write",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Maximum",
      "alias": "Cache Write",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "ShardId", "value": "ShardId" }
      ],
      "metricName": "cacheWrite",
      "metricNamespace": "Microsoft.Cache/Redis",
      "resources": [
       { "resourceGroup": "$ResourceGroup", "resourceName": "$ResourceName" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    },
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Maximum",
      "alias": "Cache Read",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "ShardId", "value": "ShardId" }
      ],
      "metricName": "cacheRead",
      "metricNamespace": "Microsoft.Cache/Redis",
      "resources": [
       { "resourceGroup": "$ResourceGroup", "resourceName": "$ResourceName" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Maximum",
      "alias": "{{dimensionvalue}}",
      "dimensionFilters": [
       { "dimension": "ErrorType", "filters": [ "*" ], "operator": "eq" }
      ],
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "ShardId", "value": "ShardId" },
       { "text": "ErrorType", "value": "ErrorType" }
      ],
      "metricName": "errors",
      "metricNamespace": "Microsoft.Cache/Redis",
      "resources": [
       { "resourceGroup": "$ResourceGroup", "resourceName": "$ResourceName" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    },
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Maximum",
      "alias": "Total Errors",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "ShardId", "value": "ShardId" },
       { "text": "ErrorType", "value": "ErrorType" }
      ],
      "metricName": "errors",
      "metricNamespace": "Microsoft.Cache/Redis",
      "resources": [
       { "resourceGroup": "$ResourceGroup", "resourceName": "$ResourceName" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    }
   ]
  },
  {
   "title": "Cache Latency & Connected Clients",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Maximum",
      "alias": "Connected Clients",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "ShardId", "value": "ShardId" }
      ],
      "metricName": "connectedclients",
      "metricNamespace": "Microsoft.Cache/Redis",
      "resources": [
       { "resourceGroup": "$ResourceGroup", "resourceName": "$ResourceName" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    },
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Average",
      "alias": "Cache latency",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "ShardId", "value": "ShardId" }
      ],
      "metricName": "cacheLatency",
      "metricNamespace": "Microsoft.Cache/Redis",
      "resources": [
       { "resourceGroup": "$ResourceGroup", "resourceName": "$ResourceName" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    }
   ]
  },
  {
   "title": "Gets & Sets",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "alias": "Gets",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "ShardId", "value": "ShardId" }
      ],
      "metricName": "getcommands",
      "metricNamespace": "Microsoft.Cache/Redis",
      "resources": [
       { "resourceGroup": "$ResourceGroup", "resourceName": "$ResourceName" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    },
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "alias": "Sets",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "ShardId", "value": "ShardId" }
      ],
      "metricName": "setcommands",
      "metricNamespace": "Microsoft.Cache/Redis",
      "resources": [
       { "resourceGroup": "$ResourceGroup", "resourceName": "$ResourceName" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    }
   ]
  },
  {
   "title": "Keys",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Maximum",
      "alias": "Total Keys",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "ShardId", "value": "ShardId" }
      ],
      "metricName": "totalkeys",
      "metricNamespace": "Microsoft.Cache/Redis",
      "resources": [
       { "resourceGroup": "$ResourceGroup", "resourceName": "$ResourceName" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    },
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "alias": "Evicted Keys",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "ShardId", "value": "ShardId" }
      ],
      "metricName": "evictedkeys",
      "metricNamespace": "Microsoft.Cache/Redis",
      "resources": [
       { "resourceGroup": "$ResourceGroup", "resourceName": "$ResourceName" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    },
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "alias": "Expired Keys",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "ShardId", "value": "ShardId" }
      ],
      "metricName": "expiredkeys",
      "metricNamespace": "Microsoft.Cache/Redis",
      "resources": [
       { "resourceGroup": "$ResourceGroup", "resourceName": "$ResourceName" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    }
   ]
  },
  {
   "title": "CPU, Memory & Server Load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Maximum",
      "alias": "{{metric}}",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "ShardId", "value": "ShardId" }
      ],
      "metricName": "percentProcessorTime",
      "metricNamespace": "Microsoft.Cache/Redis",
      "resources": [
       { "resourceGroup": "$ResourceGroup", "resourceName": "$ResourceName" }
      ],
      "timeGrain": "PT1M",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    },
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Maximum",
      "alias": "{{metric}}",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "ShardId", "value": "ShardId" }
      ],
      "metricName": "usedmemorypercentage",
      "metricNamespace": "Microsoft.Cache/Redis",
      "resources": [
       { "resourceGroup": "$ResourceGroup", "resourceName": "$ResourceName" }
      ],
      "timeGrain": "PT1M",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    },
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Maximum",
      "alias": "{{metric}}",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "ShardId", "value": "ShardId" }
      ],
      "metricName": "serverLoad",
      "metricNamespace": "Microsoft.Cache/Redis",
      "resources": [
       { "resourceGroup": "$ResourceGroup", "resourceName": "$ResourceName" }
      ],
      "timeGrain": "PT1M",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    }
   ]
  }
 ]
}