{
 "title": "Azure Key Vaults",
 "description": "The dashboard provides insights of Azure Key Vaults overview, failures and operations.",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ds",
    "label": "Datasource",
    "query": "grafana-azure-monitor-datasource"
   },
   {
    "name": "sub",
    "label": "Subscription",
    "query": {}
   },
   {
    "name": "rg",
    "label": "Resource Group",
    "query": {}
   },
   { "name": "ns", "label": "Namespace", "query": "Microsoft.KeyVault/vaults" },
   {
    "name": "resource",
    "label": "Resource",
    "query": {}
   },
   {
    "name": "location",
    "query": {}
   },
   {
    "name": "endpoint",
    "query": {}
   },
   {
    "name": "sku",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<table style=\"border-collapse: collapse; width: 100%;\">\n  <tr>\n    <td style=\"color: #6E9FFF;\">Key Vault Name:</td>\n    <td>${resource}</td>\n    <td style=\"color: #6E9FFF;\">Vault URI:</td>\n    <td>${endpoint}</td>\n  </tr>\n  <tr>\n    <td style=\"color: #6E9FFF;\">Resource Group:</td>\n    <td>${rg}</td>\n    <td style=\"color: #6E9FFF;\">SKU:</td>\n    <td>${sku}</td>\n  </tr>\n  <tr>\n    <td style=\"color: #6E9FFF;\">Location:</td>\n    <td>${location}</td>\n    <td style=\"color: #6E9FFF;\"></td>\n    <td></td>\n  </tr>\n</table>"
   },
   "targets": [
    {
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Availability, Requests and Latency",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Activity Type", "value": "ActivityType" },
       { "text": "Activity Name", "value": "ActivityName" },
       { "text": "Status Code", "value": "StatusCode" },
       { "text": "Status Code Class", "value": "StatusCodeClass" }
      ],
      "metricDefinition": "Microsoft.KeyVault/vaults",
      "metricName": "Availability",
      "metricNamespace": "Microsoft.KeyVault/vaults",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "$resource" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Activity Type", "value": "ActivityType" },
       { "text": "Activity Name", "value": "ActivityName" },
       { "text": "Status Code", "value": "StatusCode" },
       { "text": "Status Code Class", "value": "StatusCodeClass" }
      ],
      "metricDefinition": "Microsoft.KeyVault/vaults",
      "metricName": "ServiceApiResult",
      "metricNamespace": "Microsoft.KeyVault/vaults",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "$resource" }
      ],
      "timeGrain": "P1D",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Activity Type", "value": "ActivityType" },
       { "text": "Activity Name", "value": "ActivityName" },
       { "text": "Status Code", "value": "StatusCode" },
       { "text": "Status Code Class", "value": "StatusCodeClass" }
      ],
      "metricDefinition": "Microsoft.KeyVault/vaults",
      "metricName": "ServiceApiLatency",
      "metricNamespace": "Microsoft.KeyVault/vaults",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "$resource" }
      ],
      "timeGrain": "P1D",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Transactions Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Activity Type", "value": "ActivityType" },
       { "text": "Activity Name", "value": "ActivityName" }
      ],
      "metricDefinition": "Microsoft.KeyVault/vaults",
      "metricName": "ServiceApiHit",
      "metricNamespace": "Microsoft.KeyVault/vaults",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "$resource" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Overall Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Activity Type", "value": "ActivityType" },
       { "text": "Activity Name", "value": "ActivityName" },
       { "text": "Status Code", "value": "StatusCode" },
       { "text": "Status Code Class", "value": "StatusCodeClass" }
      ],
      "metricDefinition": "Microsoft.KeyVault/vaults",
      "metricName": "ServiceApiLatency",
      "metricNamespace": "Microsoft.KeyVault/vaults",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "$resource" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Activity Type", "value": "ActivityType" },
       { "text": "Activity Name", "value": "ActivityName" },
       { "text": "Status Code", "value": "StatusCode" },
       { "text": "Status Code Class", "value": "StatusCodeClass" }
      ],
      "metricDefinition": "Microsoft.KeyVault/vaults",
      "metricName": "Availability",
      "metricNamespace": "Microsoft.KeyVault/vaults",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "$resource" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Request Types over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Activity Type", "value": "ActivityType" },
       { "text": "Activity Name", "value": "ActivityName" }
      ],
      "metricDefinition": "Microsoft.KeyVault/vaults",
      "metricName": "ServiceApiHit",
      "metricNamespace": "Microsoft.KeyVault/vaults",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "$resource" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Failures",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Successes (2xx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       { "dimension": "StatusCodeClass", "filters": [ "2xx" ], "operator": "eq" }
      ],
      "dimensions": [
       { "text": "Activity Type", "value": "ActivityType" },
       { "text": "Activity Name", "value": "ActivityName" },
       { "text": "Status Code", "value": "StatusCode" },
       { "text": "Status Code Class", "value": "StatusCodeClass" }
      ],
      "metricDefinition": "Microsoft.KeyVault/vaults",
      "metricName": "ServiceApiResult",
      "metricNamespace": "Microsoft.KeyVault/vaults",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "$resource" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": ""
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Failures (4xx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       { "dimension": "StatusCodeClass", "filters": [ "4xx" ], "operator": "eq" }
      ],
      "dimensions": [
       { "text": "Activity Type", "value": "ActivityType" },
       { "text": "Activity Name", "value": "ActivityName" },
       { "text": "Status Code", "value": "StatusCode" },
       { "text": "Status Code Class", "value": "StatusCodeClass" }
      ],
      "metricDefinition": "Microsoft.KeyVault/vaults",
      "metricName": "ServiceApiResult",
      "metricNamespace": "Microsoft.KeyVault/vaults",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "$resource" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Throttling (429)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       { "dimension": "StatusCode", "filters": [ "429" ], "operator": "eq" }
      ],
      "dimensions": [
       { "text": "Activity Type", "value": "ActivityType" },
       { "text": "Activity Name", "value": "ActivityName" },
       { "text": "Status Code", "value": "StatusCode" },
       { "text": "Status Code Class", "value": "StatusCodeClass" }
      ],
      "metricDefinition": "Microsoft.KeyVault/vaults",
      "metricName": "ServiceApiResult",
      "metricNamespace": "Microsoft.KeyVault/vaults",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "$resource" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Authentication Errors (401 & 403)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       { "dimension": "StatusCode", "filters": [ "401" ], "operator": "eq" }
      ],
      "dimensions": [
       { "text": "Activity Type", "value": "ActivityType" },
       { "text": "Activity Name", "value": "ActivityName" },
       { "text": "Status Code", "value": "StatusCode" },
       { "text": "Status Code Class", "value": "StatusCodeClass" }
      ],
      "metricDefinition": "Microsoft.KeyVault/vaults",
      "metricName": "ServiceApiResult",
      "metricNamespace": "Microsoft.KeyVault/vaults",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "$resource" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       { "dimension": "StatusCode", "filters": [ "403" ], "operator": "eq" }
      ],
      "dimensions": [
       { "text": "Activity Type", "value": "ActivityType" },
       { "text": "Activity Name", "value": "ActivityName" },
       { "text": "Status Code", "value": "StatusCode" },
       { "text": "Status Code Class", "value": "StatusCodeClass" }
      ],
      "metricDefinition": "Microsoft.KeyVault/vaults",
      "metricName": "ServiceApiResult",
      "metricNamespace": "Microsoft.KeyVault/vaults",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "$resource" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  }
 ]
}